[project]
name = "etalonu-validacija"
version = "0.1.0"
description = "Display statistics of Riga city public transportation ticket validations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.1",
    "flask>=3.1.0",
    "flask-wtf>=1.2.2",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "pylint>=3.3.5",
]

[tool.ruff.format]
quote-style = "single"
