name: Weekly Vulnerability Scan

on:
  schedule:
    - cron: "0 0 * * 0" # weekly (Sunday at midnight UTC)
  workflow_dispatch: # allows manual trigger for testing

jobs:
  scan:
    runs-on: codeberg-tiny-lazy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan vulnerabilities
        uses: docker://aquasec/trivy:latest
        with:
          args: repo --exit-code 1 --format json -o report.json . --scanners vuln

      - name: Upload report for later steps
        if: "!cancelled()"
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: trivy-report
          path: report.json

  notify:
    needs: scan
    if: failure()
    runs-on: codeberg-tiny-lazy
    steps:
      - name: Download report
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          name: trivy-report

      - name: Send notification
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
          CI_REPO_NAME: ${{ github.repository }}
        run: |
          curl -X PUT "$NTFY_URL" \
          -H "title: ${CI_REPO_NAME} scan results" \
          -H "filename: ${CI_REPO_NAME}_report.json" \
          -H "priority: 2" \
          -H "tags: warning" \
          -H "Actions: view, Open explorer, https://dbsystel.github.io/trivy-vulnerability-explorer" \
          --data-binary "@report.json" \
          > /dev/null
