"""Change column data type.

Revision ID: 37a50250b000
Revises: 5a2b0423ab02
Create Date: 2024-07-04 12:09:43.495250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a50250b000'
down_revision = '5a2b0423ab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validacijas', schema=None) as batch_op:
        batch_op.alter_column('laiks',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validacijas', schema=None) as batch_op:
        batch_op.alter_column('laiks',
               existing_type=sa.String(length=32),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
