"""Initial migration.

Revision ID: 809f526c0839
Revises: 
Create Date: 2024-07-05 11:48:17.337987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809f526c0839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gar')
    )
    op.create_table('marsruts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mars_nos', sa.Text(), nullable=True),
    sa.Column('marsruts', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mars_nos'),
    sa.UniqueConstraint('marsruts')
    )
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parks', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parks')
    )
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transports')
    )
    op.create_table('validacijas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parks_id', sa.Integer(), nullable=True),
    sa.Column('transp_id', sa.Integer(), nullable=True),
    sa.Column('gar_nr_id', sa.Integer(), nullable=True),
    sa.Column('marsruts_id', sa.Integer(), nullable=True),
    sa.Column('virziens', sa.Boolean(), nullable=True),
    sa.Column('talona_id', sa.Integer(), nullable=True),
    sa.Column('laiks', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['gar_nr_id'], ['gar.id'], ),
    sa.ForeignKeyConstraint(['marsruts_id'], ['marsruts.id'], ),
    sa.ForeignKeyConstraint(['parks_id'], ['parks.id'], ),
    sa.ForeignKeyConstraint(['transp_id'], ['transports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validacijas')
    op.drop_table('transports')
    op.drop_table('parks')
    op.drop_table('marsruts')
    op.drop_table('gar')
    # ### end Alembic commands ###
