"""Initial migration.

Revision ID: a326c43ed5c2
Revises: 
Create Date: 2024-07-04 09:33:38.004599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a326c43ed5c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validacijas',
    sa.Column('Ier_ID', sa.Integer(), nullable=False),
    sa.Column('Parks', sa.String(length=64), nullable=True),
    sa.Column('TranspVeids', sa.String(length=64), nullable=True),
    sa.Column('GarNr', sa.Integer(), nullable=True),
    sa.Column('MarsrNos', sa.String(length=64), nullable=True),
    sa.Column('TMarsruts', sa.String(length=64), nullable=True),
    sa.Column('Virziens', sa.String(length=64), nullable=True),
    sa.Column('ValidTalonaId', sa.Integer(), nullable=True),
    sa.Column('Laiks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Ier_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validacijas')
    # ### end Alembic commands ###
